### ISSUE TITLE
Missing Package Requirements

### ISSUE THREAD

**Issue by ttyler3** [johnsoupir/local-assistant#2]
I attempted to install this project on a fresh Ubuntu 22 OS. I had to manually install quite a few packages manually as the scripts kept giving me errors. Here is a list:
pip
openai
paho-mqtt (had to install via pip3)

I also had to remove the requirement of 're' as it could not be found for reasons unknown to me.
Please add the missing requirements and remove re.

**Comment by johnsoupir** [comment]
The pip and paho requirements have been addressed. The openai package was already required. Is it possible the absence of pip was the cause of openai not being found?

Please try the latest commit on the feature/assistant branch.
